### ISSUE TITLE
Dear PyGui showcase

### ISSUE THREAD

**Issue by bandit-masked** [mkouhia/dearpygui-map#22]
Hey, dearpygui-map looks like it could be a nice addition to the [Dear PyGui showcase](https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase). Would you be willing to make a short GIF (<8Mb) of the app?

I'm not familiar with poetry, but I cannot get the app to run on my computer or I'd probably make the GIF myself.

**Comment by mkouhia** [comment]
Indeed! I am planning to announce it there and on Discord when I release 0.1.0. Should be within a week or so.

**Comment by bandit-masked** [comment]
That would be great! For the showcase, I'd prefer high quality and short over lower quality and long. It just needs to provide a good impression of the app.

**Comment by mkouhia** [comment]
First release is now made and a notification is posted to Discord showcase. Thanks for the patience!

**Comment by bandit-masked** [comment]
I just saw it. Looks awesome! Thanks for making and sharing the widget! Is it possible to show or stick things to the map? Or would you have to put those on a drawlist by yourself? Probably the latter, just checking to be sure ;-)

Also, preloading (or locally storing) an entire country or region would be cool as well, so it could be used offline.
